/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ServiceCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const ServiceOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'cost' : IDL.Float64,
  'link' : IDL.Text,
  'user' : IDL.Principal,
  'quantity' : IDL.Nat,
  'serviceId' : IDL.Nat,
});
export const SmmService = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'maxQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'minQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func([], [], []),
  'deposit' : IDL.Func([IDL.Float64], [], []),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(ServiceOrder)], ['query']),
  'getServicesByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SmmService)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ServiceCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ServiceOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'cost' : IDL.Float64,
    'link' : IDL.Text,
    'user' : IDL.Principal,
    'quantity' : IDL.Nat,
    'serviceId' : IDL.Nat,
  });
  const SmmService = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'maxQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'minQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func([], [], []),
    'deposit' : IDL.Func([IDL.Float64], [], []),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(ServiceOrder)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SmmService)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };