/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface ServiceCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface ServiceOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'cost' : number,
  'link' : string,
  'user' : Principal,
  'quantity' : bigint,
  'serviceId' : bigint,
}
export interface SmmService {
  'id' : bigint,
  'categoryId' : bigint,
  'maxQuantity' : bigint,
  'name' : string,
  'description' : string,
  'pricePerUnit' : number,
  'minQuantity' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<[], undefined>,
  'deposit' : ActorMethod<[number], undefined>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<ServiceCategory>>,
  'getMyOrders' : ActorMethod<[], Array<ServiceOrder>>,
  'getServicesByCategory' : ActorMethod<[bigint], Array<SmmService>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];